export const FILL_ORDER_INIT_QUERY = 'FILL_ORDER_INIT_QUERY';

export const AUDITING_QUERY = 'AUDITING_QUERY';
export const AUDITING_QUERY_SUCESS = 'AUDITING_QUERY_SUCESS';

export const COST_CENTER_QUERY = 'COST_CENTER_QUERY';
export const COST_CENTER_QUERY_SUCESS = 'COST_CENTER_QUERY_SUCESS';

export const INSURANCE_QUERY = 'INSURANCE_QUERY';
export const INSURANCE_QUERY_SUCESS = 'INSURANCE_QUERY_SUCESS';

export const INSURANCE_CHECKED = 'INSURANCE_CHECKED';
export const INSURANCE_CHECKED_SUCESS = 'INSURANCE_CHECKED_SUCESS';
