export const AUDITING_QUERY = 'AUDITING_QUERY';
export const AUDITING_QUERY_SUCESS = 'AUDITING_QUERY_SUCESS';

export const COST_CENTER_QUERY = 'COST_CENTER_QUERY';
export const COST_CENTER_QUERY_SUCESS = 'COST_CENTER_QUERY_SUCESS';