export const ADDRESS_QUERY = 'ADDRESS_QUERY';
export const ADDRESS_QUERY_SUCCESS = 'ADDRESS_QUERY_SUCCESS';
export const ADDRESS_ADD = 'ADDRESS_ADD';
export const ADDRESS_ADD_SUCCESS = 'ADDRESS_ADD_SUCCESS';
export const ADDRESS_UPDATE = 'ADDRESS_UPDATE';
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS';
export const ADDRESS_DELETE = 'ADDRESS_DELETE';
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS';