export const FLIGHT_QUERY = 'FLIGHT_QUERY';
export const FLIGHT_QUERY_SUCESS = 'FLIGHT_QUERY_SUCESS';

export const TIME_DESC_ORDER = 'TIME_DESC_ORDER';
export const TIME_ASCE_ORDER = 'TIME_ASCE_ORDER';

export const PRICE_DESC_ORDER = 'PRICE_DESC_ORDER';
export const PRICE_ASCE_ORDER = 'PRICE_ASCE_ORDER';

export const AIRLINE_QUERY = 'AIRLINE_QUERY';
export const AIRLINE_QUERY_SUCESS = 'AIRLINE_QUERY_SUCESS';