export const FLIGHT_DETAIL_QUERY = 'FLIGHT_DETAIL_QUERY';

export const ECONOMY_QUERY_SUCESS = 'ECONOMY_QUERY_SUCESS';

export const BUSINESS_QUERY_SUCESS = 'BUSINESS_QUERY_SUCESS';

export const FIRST_QUERY_SUCESS = 'FIRST_QUERY_SUCESS';