export const FLIGHT_DETAIL_QUERY = 'FLIGHT_DETAIL_QUERY';

export const ECONOMY_QUERY_SUCESS = 'ECONOMY_QUERY_SUCESS';

export const BUSINESS_QUERY_SUCESS = 'BUSINESS_QUERY_SUCESS';

export const FIRST_QUERY_SUCESS = 'FIRST_QUERY_SUCESS';

export const GPTICKET_QUERY = 'GPTICKET_QUERY';
export const GPTICKET_QUERY_SUCESS = 'GPTICKET_QUERY_SUCESS';

export const FLIGHT_DETAILS = 'FLIGHT_DETAILS';
export const RETURN_DETAILS = 'RETURN_DETAILS';