export const FLIGHT_QUERY = 'FLIGHT_QUERY';
export const FLIGHT_QUERY_SUCESS = 'FLIGHT_QUERY_SUCESS';

export const SELECT_START_CITY = 'SELECT_START_CITY';
export const SELECT_END_CITY = 'SELECT_END_CITY';
export const SELECT_START_DATE = 'SELECT_START_DATE';
export const SELECT_BACK_DATE = 'SELECT_BACK_DATE';