export const QUERY_FLIGHT_ORDER = 'QUERY_FLIGHT_ORDER';
export const QUERY_FLIGHT_ORDER_SUCCESS = 'QUERY_FLIGHT_ORDER_SUCCESS';

export const QUERY_FLIGHT_ORDER_DETAIL = 'QUERY_FLIGHT_ORDER_DETAIL';
export const QUERY_FLIGHT_ORDER_DETAIL_SUCESS = 'QUERY_FLIGHT_ORDER_DETAIL_SUCESS';

export const LOAD_MORE_ORDER = 'LOAD_MORE_ORDER';
export const LOAD_MORE_ORDER_SUCCESS = 'LOAD_MORE_ORDER_SUCCESS';
